---
- hosts: nodes
  become: yes
  vars_files: ./vars/docker.yml
  tasks:
  - name: Set timezone to Madrid
    community.general.timezone:
      name: Europe/Madrid

  - name: Update packages
    apt:
      update_cache: yes

  - name: Install required packages for Docker
    apt:
      name: "{{ packages }}"
      state: latest

  - name: Add Docker gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker official repo for Ubuntu 20.04 (focal)
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update packages
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name: docker-ce
      state: latest

  - name: Add user to docker group
    user:
      name: "{{ ansible_env.SUDO_USER }}"
      groups: docker
      append: yes

  - name: Reset connection to apply group permissions
    meta: reset_connection

  - name: Install Docker compose
    apt:
      name: docker-compose
      state: latest

  - name: Create directory for Docker compose
    become: no
    file:
      path: "{{ ansible_env.PWD }}/compose"
      state: directory

  - name: Copy compose folder to host
    become: no
    copy:
      src: "./compose"
      dest: "{{ ansible_env.PWD }}"

  - name: Deploy the Docker compose
    become: no
    docker_compose:
      project_src: "{{ ansible_env.PWD }}/compose"
